development:
  google:
    google_app_id: <%= ENV["GOOGLE_CRIENT_ID"] %>
    google_secret: <%= ENV["GOOGLE_CRIENT_SECRET"] %>
  facebook:
    facebook_app_id: <%= ENV["FACEBOOK_ID"] %>
    facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>
